In [21]:
# type: ignore
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import mglearn


def printIrisMetaData(meta_name: str):
    meta_data = iris_dataset[meta_name]
    print(f"---- {meta_name}: {type(meta_data)}\n{meta_data}\n\n")

iris_dataset = load_iris()

print(f"Keys = {iris_dataset.keys()}\n\n")
printIrisMetaData('target_names')
printIrisMetaData('feature_names')
printIrisMetaData('filename')
printIrisMetaData('data_module')
printIrisMetaData('data')
printIrisMetaData('target')


Keys = dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


---- target_names: <class 'numpy.ndarray'>
['setosa' 'versicolor' 'virginica']


---- feature_names: <class 'list'>
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


---- filename: <class 'str'>
iris.csv


---- data_module: <class 'str'>
sklearn.datasets.data


---- data: <class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]


In [ ]:
# type: ignore
import mglearn

from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state = 0
)


X_train_df = pd.DataFrame(X_train, columns=iris_dataset.feature_names)

pd.plotting.scatter_matrix(X_train_df, c=y_train, figsize=(12, 12), marker='o', 
                           hist_kwds={'bins': 20}, s=60, alpha=0.8, cmap=mglearn.cm3)

In [33]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 1)
knn.fit(X_train, y_train)

y_prediction = knn.predict(X_test)
print("True labels {}\n".format(y_test))
print("Prediction: {}\n".format(y_prediction))
print("Predicted labels: {}\n"
      .format(iris_dataset['target_names'][y_prediction])
      )

print("y_prediction == y_test: {}\n"
      .format(y_prediction == y_test))

print("Test score: {:.2f}\n"
      .format(np.mean(y_prediction == y_test))
      )

print("score: {:.2f}\n".format(
    knn.score(X_test, y_test)
))


True labels [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]

Prediction: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]

Predicted labels: ['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 'virginica' 'versicolor' 'setosa' 'setosa' 'virginica'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'setosa' 'virginica'
 'versicolor' 'setosa' 'virginica' 'virginica' 'versicolor' 'setosa'
 'virginica']

y_prediction == y_test: [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False]

Test score: 0.97

score: 0.97

