In [35]:
import numpy as np;

X = np.array([[0, 1, 0, 1],
                            [1, 0, 1, 1],
                            [0, 0, 0, 1],
                            [1, 0, 1, 0]])
y = np.array([0, 1, 0, 1])

counts = {}
for label in np.unique(y):
    print("y == label -> {}".format(y == label))
    print("X[y == label] -> {}\n".format(X[y == label]))
    counts[label] = X[y == label].sum(axis=0)

print("Feature counts\n{}".format(counts))

y == label -> [ True False  True False]
X[y == label] -> [[0 1 0 1]
 [0 0 0 1]]

y == label -> [False  True False  True]
X[y == label] -> [[1 0 1 1]
 [1 0 1 0]]

Feature counts
{np.int64(0): array([0, 1, 0, 2]), np.int64(1): array([2, 0, 2, 1])}


In [29]:
X = np.array([[1, 2, 3, 4, 5, 6],
              [1, 3, 5, 7, 4, 2]])
X >= 3

array([[False, False,  True,  True,  True,  True],
       [False,  True,  True,  True,  True, False]])